### Read All Users
GET http://localhost:3001/api/v1/users

### Create a new User
POST http://localhost:3001/api/v1/users
Content-Type: application/json

{
  "username": "scottlang",
  "email": "scottlang@example.com",
  "password": "antman123"
}

### Update an existing User
PUT http://localhost:3001/api/v1/users/1
Content-Type: application/json

{
  "username": "tonystark-updated",
  "email": "tony.updated@example.com",
  "password": "newironman123"
}

### Delete an existing User
DELETE http://localhost:3001/api/v1/users/3