@baseUrl = http://localhost:3001/api/v2

@email = nickmail@example.com
@password = nockpass

### Login
POST {{baseUrl}}/users/login
Content-Type: application/json

{

  "email":"{{email}}",
  "password":"{{password}}"
}

### Logout
POST {{baseUrl}}/users/logout

###Check user's token
GET {{baseUrl}}/users/auth


### READ all users
GET {{baseUrl}}/users 

### CREATE a new user
POST {{baseUrl}}/users 
Content-Type: application/json

{
  "username": "adminnick",
  "role":"admin",
  "email": "nickmail@example.com",
  "password": "nockpass"
}


